<Project>
	<Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<IsPackable>false</IsPackable>
		<DocumentationFile />
		<OutputType>Exe</OutputType>
		<Nullable>disable</Nullable>
	</PropertyGroup>
</Project>