on:
  workflow_call: 
    inputs:
      forRelease:
        description: 'Run for release?'
        required: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      with:
        fetch-depth: 0

    - name: Git Semantic Version
      id: version
      uses: PaulHatch/semantic-version@4d6da96a9bc3116da3613309a11ff75fba58eb8d # v6.0.4
      with:
        tag_prefix: ''
        version_format: "${major}.${minor}.${patch}${{ !inputs.forRelease && '-preview${increment}' || '' }}"
        search_commit_body: true

    - name: Setup dotnet from global.json
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6
      with:
        global-json-file: global.json

    - name: Build and Pack
      run: dotnet build -c Release -p:Version=${{ steps.version.outputs.version}}

    - name: Run tests
      run: dotnet test -c Release --no-build --report-trx --report-trx-filename "{asm}_report.trx" --coverage --coverage-output-format cobertura

    - name: Upload dotnet test results
      uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2 # v3.0.0
      if: ${{ !cancelled() }}
      with:
        name: .NET Tests
        path: 'TestResults/*_report.trx'
        reporter: dotnet-trx
        fail-on-error: true

    - name: Install ReportGenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Generate code coverage report
      run: |
        reportgenerator \
        -reports:"**/TestResults/**/*.cobertura.xml" \
        -targetDir:"codecoveragereport" \
        -reporttypes:"Html;MarkdownSummaryGitHub"

    - name: Publish code coverage summary
      run: cat codecoveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY

    - name: Upload code coverage report
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: code-coverage-report
        path: codecoveragereport

    - name: Upload package artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: packages
        path: "**/*.nupkg"