name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  checks: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      forRelease: false

  generate_docs:
    uses: ./.github/workflows/generate-docs.yml
    
  publish_package:
    needs: build
    uses: ./.github/workflows/publish-packages-myget.yml
    with:
      feedUrl: https://www.myget.org/F/mgrosperrin/api/v3/index.json
      environmentName: myget
    secrets:
      feedAPIKey: ${{ secrets.MYGET_CI_API_KEY }}
    if: github.event_name == 'push'
