on:
  workflow_call:
    inputs: {}
jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install docfx
        run: dotnet tool install -g docfx

      - name: Run DocFx
        run: docfx docs/docfx.json

      # - name: Build documenation site
      #   uses: nunit/docfx-action@v3.1.0
      #   with:
      #     args: docs/docfx.json

      - name: Upload documentation archive
        uses: actions/upload-pages-artifact@v3
        with:
          path: artifacts/_site
