on:
  workflow_call:
    inputs: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Build documentation site
        uses: wechooz/docfx-action@893328456efc0d2dc91a9ebfe9d533ca594598bc # v10.0.0
        with:
          args: docs/docfx.json

      - name: Upload documentation archive
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5
        with:
          path: artifacts/_site
  