name: Release

on:
  push:
    tags:
      - "*.*.*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  checks: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      forRelease: true

  generate_docs:
    uses: ./.github/workflows/generate-docs.yml
    
  publish_package:
    needs: [build, generate_docs]
    uses: ./.github/workflows/publish-packages-nuget.yml
    with:
      environmentName: nuget
    secrets:
      owner: ${{ secrets.NUGET_OWNER }}
    if: github.event_name == 'push'
    
  publish_docs:
    needs: [publish_package, generate_docs]
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.url }}
    runs-on: ubuntu-latest
    steps:
      - name: Publish documentation
        uses: actions/deploy-pages@v5
        id: deployment
